services:
  - type: web
    name: tagging-api
    env: docker
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /health
    buildCommand: ""  # Docker builds are automatic
    startCommand: ""  # Docker runs are automatic
    envVars:
      - key: PORT
        value: 8000